name: final_submission
description: Flutter Project for final submission on Dicoding Academy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0

  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Gabarito
      fonts:
      - asset: assets/fonts/Gabarito/Gabarito-Regular.ttf
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
